language: swift
osx_image: xcode11

rvm: 2.6.3
gemfile: Gemfile

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

    - PROJECT='HandlersKit.xcodeproj'

    - IOS_SCHEME='HandlersKit'
    - IOS_DESTINATION='platform=iOS Simulator,OS=13.0,name=iPhone 11'
    - IOS_BUILD_LOG_PATH='xcodebuild-ios.json'

    - SKIP_SWIFTLINT=TRUE

install:
  - gem update bundler
  - bundle install --without=documentation

script:
  - set -o pipefail
  - swift --version

  - xcodebuild clean build test -project "$PROJECT" -scheme "$IOS_SCHEME" -destination "$IOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="$IOS_BUILD_LOG_PATH" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'HandlersKit'

  - bundle exec pod lib lint --skip-tests --allow-warnings
  - bundle exec danger --remove-previous-comments

branches:
  only:
    - master
